export const mockHospitals = [
  {
    id: "1",
    name: "City Medical Center",
    location: "Downtown, 2.5 km away",
    distance: 2.5,
    availability: "Available" as const,
    queueTime: 15,
    specializations: ["Cardiology", "Neurology", "General"],
    doctors: [
      {
        id: "d1",
        name: "Dr. Sarah Johnson",
        specialization: "Cardiology",
        experience: 12,
        rating: 4.8,
        availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
      },
      {
        id: "d2",
        name: "Dr. Michael Chen",
        specialization: "Neurology",
        experience: 8,
        rating: 4.6,
        availableSlots: ["9:00 AM", "1:00 PM", "3:30 PM"],
      },
      {
        id: "d3",
        name: "Dr. Emily Rodriguez",
        specialization: "General",
        experience: 5,
        rating: 4.7,
        availableSlots: ["11:00 AM", "3:00 PM", "5:00 PM"],
      },
    ],
  },
  {
    id: "2",
    name: "Riverside Hospital",
    location: "North District, 4.2 km away",
    distance: 4.2,
    availability: "Available" as const,
    queueTime: 25,
    specializations: ["Orthopedics", "Pediatrics", "General"],
    doctors: [
      {
        id: "d4",
        name: "Dr. James Wilson",
        specialization: "Orthopedics",
        experience: 15,
        rating: 4.9,
        availableSlots: ["10:30 AM", "2:30 PM", "4:00 PM"],
      },
      {
        id: "d5",
        name: "Dr. Lisa Park",
        specialization: "Pediatrics",
        experience: 10,
        rating: 4.8,
        availableSlots: ["9:30 AM", "1:30 PM", "3:00 PM"],
      },
    ],
  },
  {
    id: "3",
    name: "Central Health Clinic",
    location: "West End, 3.8 km away",
    distance: 3.8,
    availability: "Full" as const,
    queueTime: 45,
    specializations: ["Cardiology", "General", "Dermatology"],
    doctors: [
      {
        id: "d6",
        name: "Dr. Robert Taylor",
        specialization: "Cardiology",
        experience: 18,
        rating: 4.9,
        availableSlots: ["11:00 AM", "3:00 PM"],
      },
      {
        id: "d7",
        name: "Dr. Amanda White",
        specialization: "Dermatology",
        experience: 7,
        rating: 4.5,
        availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
      },
    ],
  },
  {
    id: "4",
    name: "Greenfield Medical",
    location: "South Valley, 6.1 km away",
    distance: 6.1,
    availability: "Available" as const,
    queueTime: 20,
    specializations: ["Neurology", "Orthopedics", "General"],
    doctors: [
      {
        id: "d8",
        name: "Dr. David Kumar",
        specialization: "Neurology",
        experience: 11,
        rating: 4.7,
        availableSlots: ["9:00 AM", "1:00 PM", "3:30 PM"],
      },
      {
        id: "d9",
        name: "Dr. Patricia Martinez",
        specialization: "General",
        experience: 6,
        rating: 4.6,
        availableSlots: ["10:00 AM", "2:00 PM", "4:00 PM"],
      },
    ],
  },
  {
    id: "5",
    name: "Premier Care Hospital",
    location: "East Side, 5.3 km away",
    distance: 5.3,
    availability: "Available" as const,
    queueTime: 30,
    specializations: ["Pediatrics", "Cardiology", "General"],
    doctors: [
      {
        id: "d10",
        name: "Dr. Jennifer Lee",
        specialization: "Pediatrics",
        experience: 9,
        rating: 4.8,
        availableSlots: ["9:30 AM", "1:30 PM", "3:00 PM"],
      },
      {
        id: "d11",
        name: "Dr. Christopher Brown",
        specialization: "Cardiology",
        experience: 14,
        rating: 4.7,
        availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
      },
    ],
  },
  {
    id: "6",
    name: "Unity Medical Center",
    location: "Midtown, 3.2 km away",
    distance: 3.2,
    availability: "Available" as const,
    queueTime: 18,
    specializations: ["General", "Orthopedics", "Neurology"],
    doctors: [
      {
        id: "d12",
        name: "Dr. Margaret Thompson",
        specialization: "General",
        experience: 8,
        rating: 4.6,
        availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
      },
      {
        id: "d13",
        name: "Dr. Steven Garcia",
        specialization: "Orthopedics",
        experience: 13,
        rating: 4.8,
        availableSlots: ["9:00 AM", "1:00 PM", "3:30 PM"],
      },
    ],
  },
]
