export const mockHospitals = [
  {
    id: "1",
    name: "City Medical Center",
    location: "Downtown, 2.5 km away",
    distance: 2.5,
    availability: "Available" as const,
    queueTime: 15,
    specializations: ["Cardiology", "Neurology", "General"],
    doctors: [
      {
        id: "d1",
        name: "Dr. Sarah Johnson",
        specialization: "Cardiology",
        experience: 12,
        rating: 4.8,
        availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
      },
      {
        id: "d2",
        name: "Dr. Michael Chen",
        specialization: "Neurology",
        experience: 8,
        rating: 4.6,
        availableSlots: ["9:00 AM", "1:00 PM", "3:30 PM"],
      },
      {
        id: "d3",
        name: "Dr. Emily Rodriguez",
        specialization: "General",
        experience: 5,
        rating: 4.7,
        availableSlots: ["11:00 AM", "3:00 PM", "5:00 PM"],
      },
    ],
  },
  {
    id: "2",
    name: "Riverside Hospital",
    location: "North District, 4.2 km away",
    distance: 4.2,
    availability: "Available" as const,
    queueTime: 25,
    specializations: ["Orthopedics", "Pediatrics", "General"],
    doctors: [
      {
        id: "d4",
        name: "Dr. James Wilson",
        specialization: "Orthopedics",
        experience: 15,
        rating: 4.9,
        availableSlots: ["10:30 AM", "2:30 PM", "4:00 PM"],
      },
      {
        id: "d5",
        name: "Dr. Lisa Park",
        specialization: "Pediatrics",
        experience: 10,
        rating: 4.8,
        availableSlots: ["9:30 AM", "1:30 PM", "3:00 PM"],
      },
    ],
  },
  {
    id: "3",
    name: "Central Health Clinic",
    location: "West End, 3.8 km away",
    distance: 3.8,
    availability: "Full" as const,
    queueTime: 45,
    specializations: ["Cardiology", "General", "Dermatology"],
    doctors: [
      {
        id: "d6",
        name: "Dr. Robert Taylor",
        specialization: "Cardiology",
        experience: 18,
        rating: 4.9,
        availableSlots: ["11:00 AM", "3:00 PM"],
      },
      {
        id: "d7",
        name: "Dr. Amanda White",
        specialization: "Dermatology",
        experience: 7,
        rating: 4.5,
        availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
      },
    ],
  },
  {
    id: "4",
    name: "Greenfield Medical",
    location: "South Valley, 6.1 km away",
    distance: 6.1,
    availability: "Available" as const,
    queueTime: 20,
    specializations: ["Neurology", "Orthopedics", "General"],
    doctors: [
      {
        id: "d8",
        name: "Dr. David Kumar",
        specialization: "Neurology",
        experience: 11,
        rating: 4.7,
        availableSlots: ["9:00 AM", "1:00 PM", "3:30 PM"],
      },
      {
        id: "d9",
        name: "Dr. Patricia Martinez",
        specialization: "General",
        experience: 6,
        rating: 4.6,
        availableSlots: ["10:00 AM", "2:00 PM", "4:00 PM"],
      },
    ],
  },
  {
    id: "5",
    name: "Premier Care Hospital",
    location: "East Side, 5.3 km away",
    distance: 5.3,
    availability: "Available" as const,
    queueTime: 30,
    specializations: ["Pediatrics", "Cardiology", "General"],
    doctors: [
      {
        id: "d10",
        name: "Dr. Jennifer Lee",
        specialization: "Pediatrics",
        experience: 9,
        rating: 4.8,
        availableSlots: ["9:30 AM", "1:30 PM", "3:00 PM"],
      },
      {
        id: "d11",
        name: "Dr. Christopher Brown",
        specialization: "Cardiology",
        experience: 14,
        rating: 4.7,
        availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
      },
    ],
  },
  {
    id: "6",
    name: "Unity Medical Center",
    location: "Midtown, 3.2 km away",
    distance: 3.2,
    availability: "Available" as const,
    queueTime: 18,
    specializations: ["General", "Orthopedics", "Neurology"],
    doctors: [
      {
        id: "d12",
        name: "Dr. Margaret Thompson",
        specialization: "General",
        experience: 8,
        rating: 4.6,
        availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
      },
      {
        id: "d13",
        name: "Dr. Steven Garcia",
        specialization: "Orthopedics",
        experience: 13,
        rating: 4.8,
        availableSlots: ["9:00 AM", "1:00 PM", "3:30 PM"],
      },
    ],
  },
]

export const mockDoctorProfiles = [
  {
    id: "d1",
    name: "Dr. Sarah Johnson",
    email: "sarah.johnson@medconnect.com",
    specialization: "Cardiology",
    experience: 12,
    rating: 4.8,
    hospital: "City Medical Center",
    bio: "Experienced cardiologist with a passion for preventive care and patient education.",
    phone: "+1 (555) 123-4567",
    licenseNumber: "MD-2024-001",
    qualifications: [
      "MD from Harvard Medical School",
      "Board Certified in Cardiology",
      "Fellowship in Interventional Cardiology",
    ],
    availableSlots: ["10:00 AM", "2:00 PM", "4:30 PM"],
    reports: [
      {
        id: "r1",
        patientName: "John Doe",
        date: "2024-10-15",
        type: "Cardiac Assessment",
        status: "Completed",
        findings: "Normal cardiac function, no abnormalities detected.",
      },
      {
        id: "r2",
        patientName: "Jane Smith",
        date: "2024-10-14",
        type: "ECG Report",
        status: "Completed",
        findings: "Regular sinus rhythm, normal intervals.",
      },
      {
        id: "r3",
        patientName: "Robert Wilson",
        date: "2024-10-13",
        type: "Echocardiogram",
        status: "Pending",
        findings: "Under review",
      },
    ],
  },
  {
    id: "d2",
    name: "Dr. Michael Chen",
    email: "michael.chen@medconnect.com",
    specialization: "Neurology",
    experience: 8,
    rating: 4.6,
    hospital: "City Medical Center",
    bio: "Neurologist specializing in headaches, migraines, and neurological disorders.",
    phone: "+1 (555) 234-5678",
    licenseNumber: "MD-2024-002",
    qualifications: [
      "MD from Stanford University",
      "Board Certified in Neurology",
      "Specialization in Migraine Management",
    ],
    availableSlots: ["9:00 AM", "1:00 PM", "3:30 PM"],
    reports: [
      {
        id: "r4",
        patientName: "Alice Brown",
        date: "2024-10-15",
        type: "MRI Report",
        status: "Completed",
        findings: "No abnormalities detected in brain imaging.",
      },
      {
        id: "r5",
        patientName: "Charlie Davis",
        date: "2024-10-12",
        type: "EEG Report",
        status: "Completed",
        findings: "Normal electrical activity, no seizure patterns.",
      },
    ],
  },
  {
    id: "d4",
    name: "Dr. James Wilson",
    email: "james.wilson@medconnect.com",
    specialization: "Orthopedics",
    experience: 15,
    rating: 4.9,
    hospital: "Riverside Hospital",
    bio: "Senior orthopedic surgeon with expertise in joint replacement and sports medicine.",
    phone: "+1 (555) 345-6789",
    licenseNumber: "MD-2024-003",
    qualifications: ["MD from Johns Hopkins", "Board Certified in Orthopedic Surgery", "Fellowship in Sports Medicine"],
    availableSlots: ["10:30 AM", "2:30 PM", "4:00 PM"],
    reports: [
      {
        id: "r6",
        patientName: "Emma Taylor",
        date: "2024-10-15",
        type: "X-Ray Report",
        status: "Completed",
        findings: "Fracture healing progressing normally.",
      },
      {
        id: "r7",
        patientName: "Frank Miller",
        date: "2024-10-14",
        type: "MRI Report",
        status: "Completed",
        findings: "Ligament tear confirmed, surgery recommended.",
      },
      {
        id: "r8",
        patientName: "Grace Lee",
        date: "2024-10-10",
        type: "Post-Surgery Report",
        status: "Completed",
        findings: "Successful knee replacement, recovery on track.",
      },
    ],
  },
]
